### ISSUE TITLE
Incompatibility with recent ControlNet code

### ISSUE THREAD

**Issue by nistvan86** [LonicaMewinsky/frame2frame#5]
When trying to use the script on the img2img tab I get this error.
(And I also get the same error with your gif2gif extension right now)

    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 399, in run
        processed = script.run(p, *script_args)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\frame2frame\scripts\frame2frame.py", line 316, in run
        generated_frames.append(generate_frame(frame))
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\frame2frame\scripts\frame2frame.py", line 253, in generate_frame
        cn_layers = cnet.get_all_units_in_processing(orig_p)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 94, in get_all_units_in_processing
        return get_all_units(p.scripts, p.script_args)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 105, in get_all_units
        return get_all_units_from(script_args[cn_script.args_from:cn_script.args_to])
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 125, in get_all_units_from
        units.append(to_processing_unit(script_args[i]))
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 181, in to_processing_unit
        assert isinstance(unit, ControlNetUnit), f'bad argument to controlnet extension: {unit}\nexpected Union[dict[str, Any], ControlNetUnit]'
    AssertionError: bad argument to controlnet extension: <scripts.external_code.ControlNetUnit object at 0x0000014C1BDBE080>
    expected Union[dict[str, Any], ControlNetUnit]

WebUI commit: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
ControlNet commit: 8682c1e49728926bb7cc7753da8917d1ab095fb1

**Comment by LonicaMewinsky** [comment]
I'll review this now. Thanks a bunch.

**Comment by LonicaMewinsky** [comment]
Thanks @nistvan86. This was resolve with controlnet PR https://github.com/Mikubill/sd-webui-controlnet/pull/605

**Comment by nistvan86** [comment]
Thank you, yes I've seen the communication there :) It's working now!
