### ISSUE TITLE
Error loading script: frame2frame.py

### ISSUE THREAD

**Issue by msolutionsIT** [LonicaMewinsky/frame2frame#7]
I have a problem loading the script and can´t figure out a solution for that.
Do you have an idea what the problem is and how to solve it?

ERROR:
Error loading script: frame2frame.py
Traceback (most recent call last):
  File "C:\Users\Admin\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Admin\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\stable-diffusion-webui\extensions\frame2frame\scripts\frame2frame.py", line 14, in <module>
    from moviepy.editor import VideoFileClip
  File "C:\Users\Admin\stable-diffusion-webui\venv\lib\site-packages\moviepy\editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "C:\Users\Admin\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "C:\Users\Admin\stable-diffusion-webui\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "C:\Users\Admin\stable-diffusion-webui\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 4, in <module>
    import proglog
ModuleNotFoundError: No module named 'proglog'

**Comment by LonicaMewinsky** [comment]
Appears one of the dependencies (proglog) is not installed, which should occur during installation of the script. Have you tried restarting the WebUI prompt yet? I'd be interested to hear of any errors that occur during the "installing requirement" stage of startup:
![image](https://user-images.githubusercontent.com/93007558/227780534-2d13e4a9-c925-499b-9149-0eecfb4b17be.png)

Mind trying that and letting me know?

**Comment by msolutionsIT** [comment]
Thank you for your fast reply.
Ok yes proglog is not installed i checked it in 
C:\Users\Admin\stable-diffusion-webui\venv\Lib\site-packages
The other packages are installed. In StabelDiffusion directory (and the normal standard Python directory).
Stabel Diffusion folder:
![2023-03-26 17_41_38-site-packages](https://user-images.githubusercontent.com/128979759/227787399-277a9d7b-cfec-4050-bb71-bfa20b7553ca.png)

I restarted the WebUI a few times since i tried to solve the problem by myself.
I mean i think i could solve it if i install that missing package (proglog) manually but i will wait since it should work automatically and i´m available to fix this problem together for other users.

![2023-03-26 17_58_17-webui-user bat - Verknüpfung](https://user-images.githubusercontent.com/128979759/227788062-11cb7b8b-e078-4810-a9b0-be447d228504.png)
